Repository Ghaadyy/fyp, pull requests merged in 2025-01, with the labels that each got.

#16 feat: User Management + Authorization
  api/.gitignore
  api/Compiler/Parser.cs
  api/Context/TestContext.cs
  api/Controllers/TestsController.cs
  api/Controllers/UsersController.cs
  api/Middlewares/WebSocketMiddleware.cs
  api/Models/ITestsRepository.cs
  api/Models/SocketsRepository.cs
  api/Models/TestFile.cs
  api/Models/TestRun.cs
  api/Models/TestsRepository.cs
  api/Models/Token/ITokenRepository.cs
  api/Models/Token/TokenGenerator.cs
  api/Models/Token/TokenRepository.cs
  api/Models/Token/TokenResponse.cs
  api/Models/User/IUserRepository.cs
  api/Models/User/LoginModel.cs
  api/Models/User/SignUpModel.cs
  api/Models/User/User.cs
  api/Models/User/UserRepository.cs
  api/Program.cs
  api/Services/TestExecutionService.cs
  api/appsettings.Development.json
  api/fyp-backend.csproj
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Dashboard.tsx
  client/src/components/Files.tsx
  client/src/components/HomeSideBar.tsx
  client/src/components/LoginForm.tsx
  client/src/components/NavUser.tsx
  client/src/components/SignUpForm.tsx
  client/src/components/TestCreator.tsx
  client/src/context/UserContext.ts
  client/src/hooks/useAuth.ts
  client/src/layouts/RootLayout.tsx
  client/src/main.tsx
  client/src/models/TokenResponse.ts
  client/src/models/User.ts
  client/src/screens/EditorScreen.tsx
  client/src/screens/HomeScreen.tsx
  client/src/screens/LoginScreen.tsx
  client/src/screens/SignUpScreen.tsx
  client/src/shadcn/components/ui/avatar.tsx
  client/src/shadcn/components/ui/card.tsx
Labels: enhancement

#17 feat: SeeClick integration
  api/Compiler/Parser.cs
  api/Controllers/TestsController.cs
  api/Models/Token/TokenGenerator.cs
  api/Services/TestExecutionService.cs
  api/appsettings.Development.json
  seeclick/api/app.py
  seeclick/api/requirements.txt
Labels: enhancement

#18 fix: Updating test runs after new execution
  client/src/components/Dashboard.tsx
  client/src/screens/EditorScreen.tsx
Labels: bug

#22 feat: Added remove buttons for statements and tests
  client/src/components/StatementCreator.tsx
  client/src/components/StatementInput.tsx
  client/src/components/TestCreator.tsx
Labels: enhancement

#23 feat: Improve test run reporting and logs management
  api/Compiler/Parser.cs
  api/Middlewares/WebSocketMiddleware.cs
  api/Services/TestExecutionService.cs
  client/package-lock.json
  client/package.json
  client/src/components/Dashboard.tsx
  client/src/components/DataTable.tsx
  client/src/components/Files.tsx
  client/src/components/TestLogs.tsx
  client/src/components/TestRunTable.tsx
  client/src/models/Log.ts
  client/src/screens/EditorScreen.tsx
  client/src/shadcn/components/ui/collapsible.tsx
  client/src/utils/parseCode.ts
Labels: enhancement

#25 feat: Integrate element type into the SeeClick prompt
  seeclick/api/app.py
Labels: enhancement

#24 feat: Added a setup script for SeeClick Flask API
  seeclick/api/setup.sh
Labels: enhancement

#27 feat: Implemented SSE instead of WebSocket to communicate with client
  api/Compiler/Parser.cs
  api/Context/TestContext.cs
  api/Controllers/TestsController.cs
  api/Middlewares/WebSocketMiddleware.cs
  api/Models/HttpRepository.cs
  api/Models/ITestsRepository.cs
  api/Models/Logs/Assertion.cs
  api/Models/Logs/Logs.cs
  api/Models/Redis/RedisLogsRepository.cs
  api/Models/Redis/RedisProcessRepository.cs
  api/Models/TestRun.cs
  api/Models/TestsRepository.cs
  api/Program.cs
  api/Services/TestExecutionService.cs
  api/appsettings.Development.json
  api/fyp-backend.csproj
  client/src/components/Dashboard.tsx
  client/src/components/DataTable.tsx
  client/src/components/TestLogs.tsx
  client/src/models/Log.ts
  client/src/screens/EditorScreen.tsx
Labels: bug, enhancement

#28 feat: Implemented ViewRunsScreen
  api/Controllers/RunsController.cs
  api/Controllers/TestsController.cs
  api/Models/HttpRepository.cs
  api/Models/ITestsRepository.cs
  api/Models/SocketsRepository.cs
  api/Models/TestRun.cs
  api/Models/TestsRepository.cs
  api/Program.cs
  api/Services/TestExecutionService.cs
  client/src/App.tsx
  client/src/components/Dashboard.tsx
  client/src/components/DataTable.tsx
  client/src/components/Files.tsx
  client/src/components/HomeSideBar.tsx
  client/src/components/ReadOnlyEditor.tsx
  client/src/components/TestLogs.tsx
  client/src/components/TestRunTable.tsx
  client/src/models/Log.ts
  client/src/models/TestFile.ts
  client/src/models/TestRun.ts
  client/src/screens/EditorScreen.tsx
  client/src/screens/RunsScreen.tsx
  client/src/screens/ViewRunScreen.tsx
Labels: enhancement

#33 fix: Switched all IDs to UUID + enable rerun test
  api/Controllers/RunsController.cs
  api/Controllers/TestsController.cs
  api/Controllers/UsersController.cs
  api/Models/Logs/Logs.cs
  api/Models/Test/TestFile.cs
  api/Models/Test/TestRun.cs
  api/Models/User/User.cs
  api/Repository/Test/ITestRepository.cs
  api/Repository/Test/TestRepository.cs
  api/Repository/User/IUserRepository.cs
  api/Repository/User/UserRepository.cs
  api/Services/Http/HttpService.cs
  api/Services/Redis/RedisProcessService.cs
  api/Services/Test/TestExecutionService.cs
  api/Services/Token/ITokenService.cs
  api/Services/Token/TokenService.cs
  client/src/App.tsx
  client/src/components/Dashboard.tsx
  client/src/components/Files.tsx
  client/src/components/Menu.tsx
  client/src/components/TestRunTable.tsx
  client/src/context/MainContext.ts
  client/src/models/Log.ts
  client/src/models/TestRun.ts
  client/src/models/User.ts
  client/src/screens/EditorScreen.tsx
  client/src/screens/RunsScreen.tsx
  client/src/screens/ViewRunScreen.tsx
Labels: bug

#35 refactor: Implement hooks to simplify network requests + SSE
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Editor.tsx
  client/src/components/FilesTable.tsx
  client/src/components/HomeSideBar.tsx
  client/src/components/Menu.tsx
  client/src/components/TestLogDropdown.tsx
  client/src/components/TestLogs.tsx
  client/src/components/TestRunTable.tsx
  client/src/hooks/useSave.ts
  client/src/hooks/useShortcut.ts
  client/src/hooks/useTest.ts
  client/src/screens/EditorScreen.tsx
  client/src/screens/HomeScreen.tsx
  client/src/screens/RunsScreen.tsx
  client/src/screens/ViewRunScreen.tsx
  client/src/utils/sortHeader.tsx
Labels: enhancement

#36 fix: Add support for compiler CLI instead of DLL
  api/Compiler/Parser.cs
  api/Services/Test/TestExecutionService.cs
Labels: bug

#37 fix: Test execution with containers and Selenium Grid
  api/Compiler/Parser.cs
  api/Services/Test/Dockerfile
  api/Services/Test/TestExecutionService.cs
Labels: bug

#38 fix: Fixed authorization in SSE endpoints
  api/Controllers/RunsController.cs
  api/Controllers/TestsController.cs
  api/Controllers/UsersController.cs
  api/Program.cs
  api/Services/Compiler/CompilerService.cs
  api/Services/Http/HttpService.cs
  api/Services/Test/TestExecutionService.cs
  client/src/hooks/useTest.ts
Labels: bug

#39 feat: Enhance run management
  api/Controllers/RunsController.cs
  api/Controllers/TestsController.cs
  api/Middlewares/WebSocketMiddleware.cs
  api/Models/Logs/Logs.cs
  api/Models/Test/TestRun.cs
  api/Program.cs
  api/Services/Compiler/CompilerService.cs
  api/Services/Http/HttpService.cs
  api/Services/Redis/RedisLogService.cs
  api/Services/Redis/RedisProcessService.cs
  api/Services/Redis/RedisRunService.cs
  api/Services/Test/TestExecutionService.cs
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Editor.tsx
  client/src/components/EditorLoader.tsx
  client/src/components/ErrorCard.tsx
  client/src/components/ReadOnlyEditor.tsx
  client/src/components/TableLoader.tsx
  client/src/components/TestLogDropdown.tsx
  client/src/components/TestLogs.tsx
  client/src/components/TestRunTable.tsx
  client/src/hooks/useTest.ts
  client/src/hooks/useTest.tsx
  client/src/models/Log.ts
  client/src/models/TestRun.ts
  client/src/screens/EditorScreen.tsx
  client/src/screens/HomeScreen.tsx
  client/src/screens/RunsScreen.tsx
  client/src/screens/ViewRunScreen.tsx
Labels: bug, enhancement

#41 feat: Added training data generation script using YOLO + PaddleOCR + DeepSeek R1
  seeclick/scripts/.gitignore
  seeclick/scripts/constants.py
  seeclick/scripts/requirements.txt
  seeclick/scripts/schema.json
  seeclick/scripts/train_data_gen.py
Labels: enhancement

#44 fix: Add support for selenium/standalone-chrome image
  README.md
  api/Dockerfile
  api/Services/Test/TestExecutionService.cs
  compose.yaml
Labels: bug

#46 refactor: Organized client project structure
  client/src/components/auth/LoginForm.tsx
  client/src/components/auth/SignUpForm.tsx
  client/src/components/editor/EditorLoader.tsx
  client/src/components/editor/ReadOnlyEditor.tsx
  client/src/components/editor/ui/UIEditor.tsx
  client/src/components/shared/card/ErrorCard.tsx
  client/src/components/shared/dialog/AddTestDialog.tsx
  client/src/components/shared/dialog/CreateFileDialog.tsx
  client/src/components/shared/nav/HomeSideBar.tsx
  client/src/components/shared/nav/Menu.tsx
  client/src/components/shared/nav/NavUser.tsx
  client/src/components/shared/table/DataTable.tsx
  client/src/components/shared/table/TableLoader.tsx
  client/src/components/test/FilesTable.tsx
  client/src/components/test/TestLogDropdown.tsx
  client/src/components/test/TestLogs.tsx
  client/src/components/test/TestRunTable.tsx
  client/src/layouts/RootLayout.tsx
  client/src/screens/EditorScreen.tsx
  client/src/screens/HomeScreen.tsx
  client/src/screens/LoginScreen.tsx
  client/src/screens/RunsScreen.tsx
  client/src/screens/SignUpScreen.tsx
  client/src/screens/ViewRunScreen.tsx
Labels: enhancement
